apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ template "web-app.name" . }}
  labels:
    name: {{ template "web-app.name" . }}
    chart: {{ template "mongodb-on-k8s.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ default 1 .Values.app.replicaCount | int }}
  selector:
    matchLabels:
      name: {{ template "web-app.name" . }}
  template:
    metadata:
      labels:
        name: {{ template "web-app.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "jaydp17/block-cluster-node-app:{{ .Values.app.commitHash }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.app.internalPort | int }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.app.internalPort | int }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.app.internalPort | int }}
        env:
        - name: PORT
          value: {{ .Values.app.internalPort | quote }}
        - name: MONGO_URL
          value: "mongodb://{{ template "mongo.name" . }}:27017/kubernetes"
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
