---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "web-app.name" . }}
  labels:
    name: {{ template "web-app.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ if .Values.aws_ssl_arn }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.aws_ssl_arn | quote }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
{{ end }}
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    targetPort: {{ .Values.app.internalPort | int }}
    protocol: "TCP"
  - name: "https"
    port: 443
    targetPort: {{ .Values.app.internalPort | int }}
    protocol: "TCP"
  selector:
    name: {{ template "web-app.name" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongo.name" . }}
  labels:
    name: {{ template "mongo.name" . }}
spec:
  ports:
  - port: 27017
  clusterIP: None # Creates a headless service
  selector:
    name: {{ template "mongo.name" . }}
