---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb-on-k8s.name" . }}
  labels:
    name: {{ template "mongodb-on-k8s.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    targetPort: {{ .Values.app.internalPort | int }}
    protocol: "TCP"
  - name: "https"
    port: 443
    targetPort: {{ .Values.app.internalPort | int }}
    protocol: "TCP"
  selector:
    name: {{ template "mongodb-on-k8s.name" . }}
