---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "mongo.name" . }}
spec:
  selector:
    matchLabels:
      name: {{ template "mongo.name" . }}
  serviceName: {{ template "mongo.name" . }}
  template:
    metadata:
      labels:
        name: {{ template "mongo.name" . }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:3.6.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: db-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 10Gi
